spring:
  thymeleaf:
    cache: false
  jmx:
    enabled: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pegasusdb?serverTimezone=JST
    username: root
    password: mysql

mybatis:
  configuration:
    mapUnderscoreToCamelCase: true
  mapper-locations:
        - classpath*:/jp/co/internous/pegasus/model/mapper/**/*.xml

logging:
  level:
    org:
      springframework: WARN
    jp.co.internous.pegasus.model.mapper: DEBUG